if(NOT FATTEN)
    message(FATAL_ERROR "FATTEN is required")
endif()
if(NOT IMAGE)
    message(FATAL_ERROR "IMAGE is required")
endif()
if(NOT SECTORS)
    message(FATAL_ERROR "SECTORS is required")
endif()
if(NOT BOOTSECTOR)
    message(FATAL_ERROR "BOOTSECTOR is required")
endif()
if(NOT FILELIST)
    message(FATAL_ERROR "FILELIST is required")
endif()

function(run_fatten)
    execute_process(
        COMMAND "${FATTEN}" "${IMAGE}" ${ARGN}
        RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "fatten failed: ${ARGN}")
    endif()
endfunction()

function(ensure_dir _dir)
    if("${_dir}" STREQUAL "" OR "${_dir}" STREQUAL ".")
        return()
    endif()

    string(REPLACE "\\" "/" _dir "${_dir}")
    string(REGEX REPLACE "^/+" "" _dir "${_dir}")
    string(REGEX REPLACE "/+$" "" _dir "${_dir}")
    if("${_dir}" STREQUAL "")
        return()
    endif()

    string(REPLACE "/" ";" _parts "${_dir}")
    set(_path "")
    foreach(_part IN LISTS _parts)
        if("${_part}" STREQUAL "")
            continue()
        endif()
        if("${_path}" STREQUAL "")
            set(_path "${_part}")
        else()
            set(_path "${_path}/${_part}")
        endif()
        list(FIND CREATED_DIRS "${_path}" _found)
        if(_found EQUAL -1)
            run_fatten(-mkdir "${_path}")
            list(APPEND CREATED_DIRS "${_path}")
            set(CREATED_DIRS "${CREATED_DIRS}" PARENT_SCOPE)
        endif()
    endforeach()
endfunction()

file(REMOVE "${IMAGE}")
run_fatten(-format "${SECTORS}")
run_fatten(-boot "${BOOTSECTOR}")

file(STRINGS "${FILELIST}" _entries)
set(CREATED_DIRS)

foreach(_entry IN LISTS _entries)
    if("${_entry}" STREQUAL "")
        continue()
    endif()

    if(NOT "${_entry}" MATCHES "^([^=]+)=(.+)$")
        continue()
    endif()

    set(_dest "${CMAKE_MATCH_1}")
    set(_src "${CMAKE_MATCH_2}")
    string(REPLACE "\\" "/" _dest "${_dest}")
    string(REGEX REPLACE "^/+" "" _dest "${_dest}")

    if(IS_DIRECTORY "${_src}")
        ensure_dir("${_dest}")
    else()
        get_filename_component(_dir "${_dest}" DIRECTORY)
        ensure_dir("${_dir}")
        run_fatten(-add "${_src}" "${_dest}")
    endif()
endforeach()

if(DEFINED FREELDR_SYS)
    run_fatten(-add "${FREELDR_SYS}" "freeldr.sys")
endif()
if(DEFINED FREELDR_INI)
    run_fatten(-add "${FREELDR_INI}" "freeldr.ini")
endif()
