@ stdcall NPGetCaps(long)
@ stdcall NPGetConnection(wstr ptr ptr)
@ stdcall NPGetUser(wstr ptr ptr)
@ stdcall NPAddConnection(ptr wstr wstr)
@ stdcall NPAddConnection3(ptr ptr wstr wstr long)
@ stdcall NPCancelConnection(wstr long)
@ stdcall NPOpenEnum(long long long ptr ptr)
@ stdcall NPEnumResource(ptr ptr ptr ptr)
@ stdcall NPCloseEnum(ptr)
@ stdcall NPGetResourceInformation(ptr ptr ptr ptr)
@ stdcall NPGetResourceParent(ptr ptr ptr)
@ stdcall NPFormatNetworkName(wstr wstr ptr long long)
@ stdcall NPPropertyDialog(ptr long long wstr long)
@ stdcall NPGetDirectoryType(wstr ptr long)
@ stdcall NPDirectoryNotify(ptr wstr long)
@ stdcall NPGetUniversalName(wstr long ptr ptr)
