@ stdcall CpuFlushInstructionCache(ptr long)
@ stdcall CpuGetContext(ptr ptr ptr long)
@ stdcall CpuGetStackPointer()
@ stdcall CpuInitializeStartupContext(ptr ptr ptr long)
@ stdcall CpuNotifyAffinityChange(long)
@ stdcall CpuNotifyAfterFork()
@ stdcall CpuNotifyBeforeFork()
@ stdcall CpuNotifyDllLoad(wstr ptr long)
@ stdcall CpuNotifyDllUnload(ptr)
@ stdcall CpuPrepareForDebuggerAttach()
@ stdcall CpuProcessDebugEvent(ptr)
@ stdcall CpuProcessInit()
@ stdcall CpuProcessTerm()
@ stdcall CpuResetFloatingPoint()
@ stdcall CpuResetToConsistentState(ptr)
@ stdcall CpuSetContext(ptr ptr ptr long)
@ stdcall CpuSetInstructionPointer(long)
@ stdcall CpuSetStackPointer(long)
@ stdcall CpuSimulate()
@ stdcall CpuSuspendLocalThread()
@ stdcall CpuSuspendThread(ptr ptr)
@ stdcall CpuThreadInit(ptr)
@ stdcall CpuThreadTerm()
